### ISSUE TITLE
Code und HTML trennen? 

### ISSUE THREAD

**Issue by STX2k** [applejuicenet/phpgui#1]
Ist in Zukunft geplant html und Code zu trennen?

**Comment by red171** [comment]
Ja!
Wie du in der `index.php` vom login siehst, habe ich damit auch schon zum Teil angefangen.

Ich bin mir nur noch nicht sicher, ob ich hier noch `twig` mit einsetze, oder nicht.

Eigentlich würde ich die phpGUI gerne komplett `native` lassen, so das keine externen Abhängigkeiten nötig sind.

Mein persönliches Ziel ist es, alles so umzuschreiben, das es `frameless` ist, und ich dann ein [bulma](https://bulma.io/) Style entwickeln kann.

Bedenke aber bei der phpGUI: der original Code von `UP` ist aus dem Jahr 2006/2007. Das wurde noch alles mit PHP 4 entwickelt, via `vim`...

**Comment by STX2k** [comment]
Nice. Das klingt super. Find ich richtig gut das du das angehst und die gui ins Jahr 2020 hebst. Danke für die schnelle Info.
